--- 
AWSTemplateFormatVersion: '2010-09-09'
Description: This is the EC2 stack to deploy the compute platform.
Resources: 
  
  
  MyInstance: 
    Properties: 
      AvailabilityZone: ca-central-1a
      ImageId: ami-0687cfe4923f5f229
      InstanceType: t2.micro
      SecurityGroups: 
        - ServerSecurityGroup
        - SSHSecurityGroup
    Type: AWS::EC2::Instance
  
  MyEIP: 
    Properties: 
      InstanceId: MyInstance
    Type: AWS::EC2::EIP

  SSHSecurityGroup: 
    Properties: 
      GroupDescription: "Enable Security for Server"
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: TCP
          ToPort: 1200
    Type: AWS::EC2::SecurityGroup
  
  ServerSecurityGroup: 
    Properties: 
      GroupDescription: "Enable Security for Server"
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: TCP
          ToPort: 1100
    Type: AWS::EC2::SecurityGroup
