--- 
AWSTemplateFormatVersion: '2010-09-09'
Description: This is the EC2 stack to deploy the compute platform - version1.0
Resources: 

  MyInstance: 
    Properties: 
      AvailabilityZone: ca-central-1a
      ImageId: ami-0101734ab73bd9e15
      InstanceType: t2.micro
      SecurityGroups: 
        - !Ref ServerSecurityGroup
        - !Ref SSHSecurityGroup
    Type: "AWS::EC2::Instance"

  
  MyEIP:
    Properties:
      InstanceId: !Ref MyInstance
    Type: "AWS::EC2::EIP"

  CoreVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: dedicated
      Tags:
        - Key: ServiceTier
          Value: NonProduction

  SSHSecurityGroup:
    Properties:
      GroupDescription: "Enable Security for Server"
      VpcId: !Ref CoreVPC
      SecurityGroupIngress:
        -
          CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: TCP
          ToPort: 22
    Type: "AWS::EC2::SecurityGroup"
  
  ServerSecurityGroup: 
    Properties: 
      GroupDescription: "Enable Security for Server"
      VpcId: !Ref CoreVPC
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: TCP
          ToPort: 80
    Type: "AWS::EC2::SecurityGroup"


Outputs:
  MyInstanceIP:
    Description: EC2 public IP
    Value: !GetAtt MyInstance.PublicIp
